# Generated by Django 3.0.6 on 2020-05-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200520_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='sha256op',
            name='ptype',
            field=models.CharField(default='PARAMETER', max_length=30),
        ),
    ]
