# Generated by Django 3.0.6 on 2020-05-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_sha256op_ptype'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='generated',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
